### ISSUE TITLE
Wrong samples in environment variables for offer letter bot

### ISSUE THREAD

**Issue by pirnz** [r3ksk/hxmrpava#1]
In this page: https://github.com/r3ksk/hxmrpava/tree/main/Automation/04-Download_Execute_Offer_Letter_Automations

There's two wrong sample values for the environment variables:

- inputFilePathSFOfferLetter: Should be a path to an excel file, like `C:\Temp\Input\file.xlsx`
- OfferType: Should be one of the four options, like `Online offer`

Regards,
Pedro

**Comment by r3ksk** [comment]
fixed this Pedro, thank you.
